package:
  name: cgal4py
  version: "0.2.1"

source:
  # path: ../
  fn: cgal4py-0.2.1.tar.gz
  url: https://pypi.python.org/packages/1e/e6/909298e28b60b2c6882cba51e493a89da2fe50a615fec4378744a53961ef/cgal4py-0.2.1.tar.gz
  md5: 05fe75acdac7e2fbad91b835cfa9ccda
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  script:
    - flake8 . -v --config=.flake8rc
    - nosetests --verbose
    - python setup.py install
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cgal4py = cgal4py:main
    #
    # Would create an entry point called cgal4py that calls cgal4py.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - nose
    - flake8
    - cython
    - numpy
    - cykdtree
    - boost
    - eigen3
    - cgal >=4.9

  run:
    - python
    - cython
    - numpy
    - scipy
    - matplotlib
    - nose
    - mpi4py
    - cykdtree
    - boost
    - eigen3
    - cgal >=4.9
    # Python 2 only
    - multiprocessing

test:
  # Python imports
  imports:
    - cgal4py
    - cgal4py.delaunay
    - cgal4py.domain_decomp
    - cgal4py.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    - nose

about:
  home: https://langmm@bitbucket.org/langmm/cgal4py
  license: BSD License
  summary: 'Python interface for CGAL Triangulations'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
